### ISSUE TITLE
--defaultrepo is not working

### ISSUE THREAD

**Issue by Spanni26** [openSUSE/mksusecd#25]
The Option "--defaultrepo" seems not to work.
If a initrd from a media created with mksusecd is unpacked, there is no file "/etc/linuxrc.d/60_mksusecd"

The code in line 2165...is that really working? The initrd is a xz compressed cpio archive...can you append something with a simple "cat >>"?

**Comment by wfeldt** [comment]
Yes, it works. You can't simply unpack the archive, though.

The kernel accepts a sequence of (optionally compressed) cpio archives. cpio itself does not.

I use a special script to unpack the initrd. But in general have to actually boot the initrd and have a look.
