### ISSUE TITLE
Minimal ISO Install like Ubuntu Server LTS

### ISSUE THREAD

**Issue by marcoczen** [openSUSE/mksusecd#44]
Hi ... Is it possible to create a custom ISO ( off  the main Leap 15.1 ISO ) but with everything stripped out except server components ? Like Ubuntu Server LTS of approx 700MB? 

Ultimately I am looking for an ISO of about 600-7000 MB for a quick LAMP installation.

**Comment by wfeldt** [comment]
mksusecd can only do that if the repo has already been split into several sub-parts like it has been done for the SLES products. For Leap/Tumbleweed you'd have to cut down the package list manually; mksusecd is no help here.
