### ISSUE TITLE
Broken link to kiwi documentation

### ISSUE THREAD

**Issue by binary-sequence** [openSUSE/mksusecd#46]
In README.md there is a link to https://suse.github.io/kiwi which redirects (301) to https://opensource.suse.com/kiwi which is not found (404).

What should be the right link here?

**Comment by binary-sequence** [comment]
ok, found https://opensuse.github.io/kiwi/ 😆

**Comment by m0rbo** [comment]
This link still looks old and not correct.
Should it be here instead?
https://osinside.github.io/kiwi/

**Comment by wfeldt** [comment]
Or both. I'm planning a doc makeover anyway and will keep this in mind.

Thanks for noting!
