### ISSUE TITLE
mksusecd not working with Tumbleweed kernel RPM's and ISO's

### ISSUE THREAD

**Issue by hanzyd** [openSUSE/mksusecd#62]
When running on TW kernel.rpm and ISO it complains “oops, incompatible initrd layout”.
It is working fine with SLE kernel and ISO’s. Something in the packaging, Modules are not under /lib/, but in /usr/…
Or another issue ”Couldn’t determine kernel version. No kernel package?”, because there is no “/boot/System.map”
in TW rpm package.

**Comment by wfeldt** [comment]
I've fixed the kernel issue but I didn't see the 'incompatible initrd layout' issue. Which ISO were you using and what did you do exactly?

BTW, I opened a separate bug  in bugzilla for SLE release tracking.

**Comment by hanzyd** [comment]
I see "oops, incompatible initrd layout" when I use kernel.rpm's build from SLE15-SPx branches and openSUSE-Tumbleweed-XFCE-Live-aarch64-Current.iso.

**Comment by hanzyd** [comment]
Indeed openSUSE-Tumbleweed-DVD-aarch64-Snapshot20221206-Media.iso is working fine.

Thank you!
